const mainTheme = {
  PRIMARY: '#EE6C4D',
  SECONDARY: '#F7C59F',
  INVERSE: '#E1E5EE',
  DEFAULT: '#3D5A80',
  BACKGROUND: '#E1E5EE',
  BACKGROUND_ACCENT: '#C7CCDB',
  BACKGROUND_GRAY: '#E1E5EE',
  BORDER_GRAY: '#C7CCDB',
  LIGHT_GRAY: '#3D5A80',
  LIGHTER_GRAY: '#E1E5EE',
  BLACK: '#293241',
  ERROR: '#E74C3C',
  WHITE: '#ffffff'
}

export const mainThemeReplicate = {
  PRIMARY: '#102E4A',
  SECONDARY: '#F7C59F',
  INVERSE: '#E1E5EE',
  DEFAULT: '#767B91',
  BACKGROUND: '#E1E5EE',
  BACKGROUND_ACCENT: '#C7CCDB',
  BACKGROUND_GRAY: '#E1E5EE',
  BORDER_GRAY: '#C7CCDB',
  LIGHT_GRAY: '#767B91',
  LIGHTER_GRAY: '#E1E5EE',
  BLACK: '#2A324B',
  ERROR: '#E74C3C',
  WHITE: '#ffffff'
}

export const experimental = {
  PRIMARY: '#FF5A5F',
  SECONDARY: '#F7C59F',
  INVERSE: '#E1E5EE',
  DEFAULT: '#767B91',
  BACKGROUND: '#E1E5EE',
  BACKGROUND_ACCENT: '#C7CCDB',
  BACKGROUND_GRAY: '#E1E5EE',
  BORDER_GRAY: '#C7CCDB',
  LIGHT_GRAY: '#767B91',
  LIGHTER_GRAY: '#E1E5EE',
  BLACK: '#2A324B',
  ERROR: '#E74C3C',
  WHITE: '#ffffff'
}

export default mainTheme
